POST http://localhost:3001/api/patients 
Content-Type: application/json

{
  "name": "Matti Paavilainen",
  "dateOfBirth": "1960-03-03",
  "ssn": "090870-3045",
  "gender": "male",
  "occupation": "cop"
}

